language: node_js
dist: trusty
node_js:
  - '8'
before_install:
  - npm i -g npm@6
script:
  - npm run lint && npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.json -X fix
