language: node_js
dist: trusty
node_js:
  - '8'
before_install:
  - npm i -g npm@6
script:
  - npm run coverage
after_success:
  - npm i -g codecov
  - codecov --file=coverage/lcov.info --disable=search
